version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    groups:
      safe-app-dependencies:
        update-types:
          - minor
          - patch
      major-app-dependencies:
        update-types:
          - major
    commit-message:
      prefix: deps
      prefix-development: deps(dev)
    cooldown:
      default-days: 10
      semver-major-days: 60
      semver-minor-days: 14
      semver-patch-days: 7
  - package-ecosystem: npm
    directory: /functions
    schedule:
      interval: monthly
    groups:
      safe-function-dependencies:
        update-types:
          - minor
          - patch
      major-function-dependencies:
        update-types:
          - major
    commit-message:
      prefix: deps
      prefix-development: deps(dev)
    cooldown:
      default-days: 10
      semver-major-days: 60
      semver-minor-days: 14
      semver-patch-days: 7
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      ci-dependencies:
        dependency-type: production
    cooldown:
      default-days: 10
